### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by unixorn** [bossjones/boss-docker-zsh-plugin#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you don't have one in mind,  I recommend [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by bossjones** [comment]
So sorry I missed this, geeze from a while back ago! Wow, i'll add one now!

**Comment by bossjones** [comment]
https://github.com/bossjones/boss-docker-zsh-plugin/pull/2
